import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Topbar from "@/components/topbar";
import withDB from "@/lib/middleware/db.middleware";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [products, setProducts] = useState([
    { name: "pc" },
    { name: "laptop" },
  ]);
  const [newProduct, setNewProduct] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topbar />
        <div className="w-[80%] m-auto p-10">
          <div className="flex flex-col w-96 gap-4 m-auto">
            <input
              className="input input-bordered"
              value={newProduct}
              onChange={(e) => setNewProduct(e.target.value)}
              placeholder="enter your product name"
            />
            <button
              className="btn"
              onClick={() =>
                setProducts((state) => [...state, { name: newProduct }])
              }
            >
              Add Item
            </button>
          </div>

          <div className="flex  flex-col w-96 gap-4 m-auto mt-4">
            {products.map((product, index) => (
              <div
                key={index}
                className={
                  "slide-in flex justify-between items-center p-2 px-4 hover:shadow-secondary shadow-lg bg-secondary text-base-100 rounded-xl text-center"
                }
              >
                <div className="text-2xl font-bold">{product.name}</div>
                <button
                  className="btn btn-ghost text-2xl"
                  onClick={() => {
                    setProducts((state) => {
                      state.splice(index, 1);
                      return [...state];
                    });
                  }}
                >
                  x
                </button>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

// export async function getStaticProps(){
//   const productsRes = await fetch("https://fakestoreapi.com/products/")
//   const products = await productsRes.json()
//   console.log(products)
//   return {
//     props:{
//       products:products
//     }
//   }
// }
